print("Vion plaza, the retail division of the multidimensional and multinational Vion plaza has always been known as a trend setter of the retail industry in")
print("the region. Today, Vion plaza symbolizes quality retailing with 10 stores and is immensely popular with the discerning shoppers across the world.")
print("With its pleasant and novel variation from the usual supermarkets,Vion plaza offers an ultra-modern shopping ambience by integrating all")
print("conceivable needs of the consumers under one roof.Vion plaza have extensively laid out counters, sprawling parking spaces,")
print(" food court  besides a panoply of international and regional brands aptly justifying")
print("its tagline, Vion plaza, .")
print("Vion plazanot only dot the cities of the Qatar but have become the most preferred shopping destinations in GCC,Canada, India,Korea and Malaysia.")
print("Our Vision")
print("To become a truly global retail brand by retaining our No.1 position in the organized retail sector of the regions we operate in and strive to be the most preferred")
print("employer for our current and future multi-ethnic employees.")
print("     ")
print("Our Mission")
print("To provide a unique shopping experience to our customers with unmatched quality in terms of products & services, while continuously")
print("exploring new market opportunities and adding value to all our business associates")
print(" ")
print("Our Values")
print("Integrity")
print("Teamwork")
print("Accountability")
print("Innovation")
print("Commitment")
print("-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------")
