while True:
    print("1.Page_One")
    print("2.Page_Two")
    print("3.Page_Three")
    print("4.Page_Four")
    ch=int(input("Enter your choice"))
    if (ch==1):
        print("Terms and Conditions")
        print("These Terms and Conditions govern your use of the -------, the Vion Plaza stores (Hypermarket, Fresh Supermarket, and Express), the terms of any purchases that you make via LuLu stores and luluhypermarket.com site, and your relationship with LuLu Hypermarket (“LuLu”, “luluhypermarket.com ”, “we” or “us”). Please read them carefully as they affect your rights and liabilities under the law. By using the site and/or registering on the site, you agree to these Terms and Conditions and to our Privacy and Cookies Policy.")
        print("1. BASIS OF USE OF THE VION PLAZA SITE")
        print(" ")
        print("1.1 The vionplaza.com site is provided to you free of charge for your personal use subject to these Terms and Conditions and our Privacy Policy. By using the Vion Plaza.com site you agree to be bound by these Terms and Conditions and our Privacy Policy.")
        print(" ")
        print("1.2 These Terms and Conditions govern your use of the Vion Plaza.com site in general, the products that you purchase in Vion Plaza stores and on the Vion Plaza.com site and all services provided in connection with them.")
        print("")
        print("2. REGISTRATION")
        print(" ")
        print("2.1 To register on the Vion Plaza.com site you must be over eighteen years of age.")
        print(" ")
        print("2.2 You must ensure that the details provided by you on registration or at any other time are correct and complete.")
        print(" ")
    elif(ch==2):
        print("3. AMENDMENTS")
        print(" ")
        print("We may update these Terms and Conditions at any time by revising details of this page. We recommend that you visit this page every now and then to see the changes made, as they are binding on you whenever you choose to continue purchasing products in our stores and the Vion Plaza.com online shop, and if you continue to use the site. ")
        print("")
        print("These Terms and Conditions were last updated on 8th May 2019.")
        print("")
        print("4. DESCRIPTIONS AND PRICES OF PRODUCTS")
        print("")
        print("4.1 We have taken care to describe and show products as accurately as possible. Despite this, products may vary from their descriptions, product images are for representation purposes only and may vary slightly from the actual product. If there is anything that you do not understand, or if you wish to obtain further information, please contact customer services (see paragraph 25 below for contact details). Descriptions/performances of products stated against each are based on the catalogue and technical literature printed by the manufacturers/agent. Therefore, the write up provided against each product is not that of luluhypermarket.com and subject to change without prior notice.")
        print("")
        print("4.2 Price may sometimes differ between Vion Plaza Stores and Vion Plaza.com; you will be charged the price on the Vion Plaza.com upon use of this site. We are under no obligation to honour any in-store price or promotion in the event that it differs from those on the Vion Plaza.com site.")
        print("")
        print("4.3 If, by mistake, we have underpriced a product, we will not be liable to supply that product to you at the stated price, provided that we notify you before we dispatch the product to you. In those circumstances, we will notify the correct price to you so you can decide whether or not you wish to order the product at that price. If you decide not to order the product, we will give you a full refund on any amount already paid for that product in accordance with our refund policy in paragraphs 16 & 17 below.")
        print("")
        print(".44 The payment may be processed prior to luluhypermarket.com dispatch of the product that you have ordered. If we have to cancel the order after we have processed the payment, the said amount will be reversed back to your credit card account. No cash disbursement shall be made under any condition whatsoever.")
        print("")
        print("4.5 The price of a product does not include the delivery charge, which will depend on the delivery method you choose and will be added during checkout. See paragraph 15 below.")
        print("")
        print("5. ACCEPTANCE OF ORDERS")
        print("")
        print("5.1 Your order is an offer to buy from us. We will send you an order acknowledgement email detailing the products you have ordered.")
        print("")
        print("5.2 Nothing that we do or say will amount to any acceptance of your offer until we send you an email notifying you of the order acknowledgment. At this point, a contract will be made between us for you to buy and for us to sell the products that you have ordered from us.")
        print("")
        print("5.3 After the time the contract is made, you cannot amend your order (but please see your right to cancel an order in paragraph 15 below).")
        print("")
        print("5.4 At any point up until the contract is made, we may decline to supply a product to you. If we decline to supply a product to you and you have already paid for it, we will give you a full refund of any amount already paid for that product in accordance with our refund policy in paragraphs 16 & 17 below.")
        print("")
    elif(ch==3):
        print("6. DELIVERIES")
        print("")
        print("6.1 Delivery will be made to the address specified when you complete the order. At point of delivery, identity verification of the Consignee by sighting either an original labour card, passport, driving license, Emirates ID, Free zone ID to support consignee verification, will be required by our courier partners.")
        print("")
        print("6.2 Please note that we do not do international shipping.")
        print("")
        print("7. CANCELLING YOUR ORDER IF YOU CHANGE YOUR MIND")
        print("")
        print("7.1 If you the customer cancel the order, vionplaza.com shall cancel the order as per your request. However, the online transaction charges will not be refunded. The cost of delivering and re-picking charges will apply if the product has been shipped. luluhypermarket.com will not be able to cancel orders that have already been shipped. luluhypermarket.com has the full right to demonstrate whether an order has been shipped or not. The customer agrees not to dispute the decision made by luluhypermarket.com and accept luluhypermarket.com decision regarding the cancellation.")
        print("")
        print("7.2 For details of how to cancel your order please visit our returns and refunds page or contact customer support on 600540048.")
        print("")
        print("8.. FAULTY PRODUCTS")
        print("")
        print("If your products arrive damaged or they are faulty, you may return them and obtain a refund or replacement product. Please visit our returns and refunds for details of how to return them and details of our replacement and refund policy.")
        print("")
        print("9. REFUNDS ON ")
        print("")
        print("If you are entitled to a refund, we will refund you")
    elif(ch==4):
        print("10. PAYMENTS AND CARDS")
        print("")
        print("10.1 Payment for your products will be taken at the time you place your order. Payments are done via Emirates NBD operating on a professional third-party cyber source payment gateway.")
        print("")
        print("10.2 Your credit/debit card details will be encrypted to the highest standard and held on the Cyber source Host payment gateway, secure from hackers.")
        print("")
        print("10.3 When ordering from the luluhypermarket.com, we accept orders only from web browsers that permit communication through Secure Socket Lawyer (SSL) technology, for example a 7.0 version or higher of Internet Explorer, version 3.5 or higher of Firefox, Chrome version 10 or higher and Safari version 5 of higher. This means that you cannot inadvertently place an order through an unsecured connection.")
        print("")
        print("10.4 All customers will be charged in local currency relating to the country of order. If a foreign currency credit card is used, then any differences between approximation in any foreign currency and actual billing price on the customer’s card bill statement is probably attributable to different credit card companies charging different exchange rates.")
        print("")
        print("11. FREE GIFTS AND PROMOTIONAL PRODUCTS")
        print("")
        print("11.1 Free gifts and promotional products that are given away in conjunction with a purchase may be dispatched to you separately and delivery times may vary.")
        print("")
        print("11.2 If you change your mind and return your product, you must also return any free gift or promotional product associated with the promotion and received by you as a result of that order. We may charge you a reasonable amount for the free gift if you do not return it.")
        print("")
        print("12 AMENDMENTS")
        print("")
        print("We may update these Terms & Conditions from time to time and any changes will be notified to you via the e-mail address provided by you on registration or via a suitable announcement on the Vion Plaza.com site. The changes will apply to the use of the Vion Plaza.com site after we have given notice. If you do not wish to accept the new Terms and Conditions, you should not continue to use the Vion Plaza.com site (including purchasing any products on the Vion Plaza.com site). If you continue to use the Vion Plaza.com site after the date on which the change comes into effect, your use of the Vion Plaza.com site indicates your agreement to be bound by the new Terms and Conditions.")
        print("")
        print("13. OUR RESPONSIBILITY TO YOU")
        print("")
        print("13.1 The Vion Plaza.com site is provided by Vion Plaza LLC without any warranties or guarantees.")
        print("")
        print("13.2 The Vion Plaza.com site may provide content from other internet sites or resources and while Vion Plaza.com tries to ensure that material included on the Vion Plaza.com site is correct, reputable and of high quality, it cannot accept responsibility if this is not the case. Vion Plaza.com will not be responsible for any errors or omissions or for the results obtained from the use of such information or for any technical problems, you may experience with the Vion Plaza.com site. If Vion Plaza.com is informed of any inaccuracies in the material on the Vion Plaza.com site, we will attempt to correct the inaccuracies as soon as we reasonably can.")
        print("")
        print("13.3 In particular, we disclaim all liabilities in connection with the following:")
        print("-          Incompatibility of the vionplaza.com site with any of your equipment, software or telecommunications links; and")
        print("-          Technical problems including errors or interruptions of the VionPlaza.com site.")
        print("")
        print("13.4 If we are in breach of these Terms and Conditions, we will only be responsible for any losses that you suffer as a result to the extent that they are a foreseeable consequence to both of us at the time you order the relevant product or the time you otherwise use the luluhypermarket.com site.")
        print("")
        print("13.5 Because we sell products for personal use only, our responsibility to you shall not include any business losses, such as lost data, lost profits, lost sales or business interruption.")
        print("")
        print("14. CUSTOMER SERVICES")
        print("")
        print("If you have any queries about online matters, please contact us online vion@vionplaza.com or via telephone: 600 54 00 48 Saturday - Thursday 8.00 AM to 9.00 PM; Friday 2.00 PM to 9.00 PM. For retail concerns, please email us at customerservice@luluhypermarket.com.")
    elif (ch==0):
        break
    else:
        print("Invalid choice")
    
